import classNames from "@/lib/classnames";
import type { ComponentProps } from "react";

export function Code({
	className,
	...props
}: ComponentProps<"code"> & { "data-theme"?: string }) {
	// Don't style <pre><code></pre> components (generated by rehype pretty code)
	const classes = classNames(className, "font-mono tracking-normal", {
		"font-[500] select-all after:content-(--backtick) before:content-(--backtick)":
			props["data-theme"] == null,
	});

	return <code {...props} className={classes} />;
}
